live_config_reload = true
working_directory = "None"

[bell]
animation = "EaseOutExpo"
duration = 1

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#7c8f8f"
blue = "#78c2ff"
cyan = "#85dc85"
green = "#36c692"
magenta = "#ae81ff"
red = "#ff5189"
white = "#e2637f"
yellow = "#bfbf97"

[colors.cursor]
cursor = "#9e9e9e"
text = "#080808"

[colors.normal]
black = "#373c40"
blue = "#80a0ff"
cyan = "#79dac8"
green = "#8cc85f"
magenta = "#d183e8"
red = "#ff5454"
white = "#a1aab8"
yellow = "#e3c78a"

[colors.primary]
background = "#080809"
bright_foreground = "#eeeeee"
foreground = "#b2b2b2"

[colors.selection]
background = "#b2ceee"
text = "#080808"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
unfocused_hollow = true

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "alacritty"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "full"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"
title = "Alacritty"

[keyboard]
bindings = [
{ key = "Return", mods = "Command", action = "ToggleSimpleFullScreen"},
]
