#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
fpath=(~/.zfunc $fpath)
fpath=(/usr/local/share/zsh-completions $fpath)

# Homebrew completions
if type brew &>/dev/null
then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

  autoload -Uz compinit
  compinit
fi

source "$HOME/.config/base16-shell/base16-shell.plugin.zsh"

# No lag after we hit esc
export KEYTIMEOUT=1
bindkey '^r' history-incremental-search-backward
# ctrl-w removed word backwards
bindkey '^w' backward-kill-word

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Custom unix utilities
if type exa &> /dev/null
then
  alias ls='exa'
  alias ll='exa -l --icons --git'
  alias lt='exa -l --icons --git --tree'
  alias lll='exa -la --icons --git'
fi

if type nvim &>/dev/null
then
  alias vim='nvim'
  export EDITOR='nvim'
  export VISUAL='nvim'
fi

alias dark='base16_rose-pine-moon'
alias bright='base16_rose-pine-dawn'
unalias sl &> /dev/null


if type starship &>/dev/null
then
  eval $(starship init zsh)
fi



export WASMTIME_HOME="$HOME/.wasmtime"
export PATH="$WASMTIME_HOME/bin:$PATH"

# Custom fzf config if exists
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
# Custom zshrc if exists
[ -f ~/.custom.zshrc ] && source ~/.custom.zshrc
